FROM python:3.6-alpine as build
RUN apk update && apk add build-base
RUN pip install greenlet

WORKDIR /tmp/site-packages
RUN cp -r /usr/local/lib/python3.6/site-packages/greenlet-0.4.14.dist-info .
RUN cp -r /usr/local/lib/python3.6/site-packages/greenlet.*.so .