FROM python:3.6-alpine3.8 as build
RUN apk update && apk add build-base
RUN pip install gevent

WORKDIR /tmp/site-packages

RUN cp -r /usr/local/lib/python3.6/site-packages/gevent .
RUN cp -r /usr/local/lib/python3.6/site-packages/greenlet.*.so .
RUN cp -r /usr/local/lib/python3.6/site-packages/gevent-*dist-info .
RUN cp -r /usr/local/lib/python3.6/site-packages/greenlet-*dist-info .
